# Generated by Django 3.0.3 on 2020-02-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='imagem',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
