# Generated by Django 3.0.3 on 2020-02-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='imagem',
            field=models.ImageField(blank=True, default='', upload_to='mediafiles'),
        ),
    ]
