# Generated by Django 3.0.3 on 2020-02-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200207_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
    ]
